# Assignment 1 - find out how to use the enumerate() fumction

In [12]:
# The enumerate function in pyhton.
# The enumerate() function is a built-in function in Python that returns an enumerate object. 
# An enumerate object is a sequence of tuples where each tuple consists of an index and the corresponding 
# value from a given iterable. In other words, the enumerate() function 
# adds a counter to an iterable and returns it as an enumerate object. For example:

s = [1,3,4,5,6]
l = [5,6,8,9,3]

for i in enumerate(s):
    print(i)

(0, 1)
(1, 3)
(2, 4)
(3, 5)
(4, 6)


In [2]:
s = [1,3,4,5,6]
l = [5,6,8,9,3]

for i in enumerate(s + l):
    print(i)

(0, 1)
(1, 3)
(2, 4)
(3, 5)
(4, 6)
(5, 5)
(6, 6)
(7, 8)
(8, 9)
(9, 3)


# Assignment 2, try how to create random numbers in numpy

In [4]:
# This is a very common way to generate random integers in NumPy. 
#The "j" variable will contain a NumPy array of random integers between 5 and 10. 
#The number of elements in the array will be determined by the size of the array you initialize "j" with. 
#For example, if you initialize "j" with "j = np.random.randint(5, 10, 3)", 
# you will get an array of 3 random integers between 5 and 10.
import numpy as np
j = np.random.randint(5,10)
print(j)

8


In [5]:
j = np.random.randint(5,10)
print(j)

5


In [6]:
j = np.random.randint(5,10,3)
print(j)

[6 7 5]


In [7]:
j = np.random.randint(5,10,4)
print(j)

[8 7 6 8]


In [8]:
j = np.random.randint(5,10,2)
print(j)

[6 5]


# Assignment 3 - Try reshaping arrays

In [9]:
# Reshaping change the position of the rows and columes as can be seen below.
#

a = np.array([2, 3, 5, 4])
b = np.array([1, -3, 4, 9])

print(a.shape)
print(b.size)

(4,)
4


In [10]:
a = np.array([[2, 3, 5, 4], [1, -3, 4, 9]])

print(a.shape)

(2, 4)


In [11]:
a.reshape(4,2)

array([[ 2,  3],
       [ 5,  4],
       [ 1, -3],
       [ 4,  9]])