In [2]:
a = [2, 3, 5, 4]
b = [1, -3, 4, 9]
list(map(lambda a,b: a + b, [2, 3, 5, 4],[1, -3, 4, 9]))

[3, 0, 9, 13]

In [3]:
a = [2, 3, 5, 4]
b = [1, -3, 4, 9]
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[3, 0, 9, 13]


In [4]:
a = 2, 3, 5, 4
b = 1, -3, 4, 9
list(zip(a,b))

[(2, 1), (3, -3), (5, 4), (4, 9)]

In [7]:
a = 2, 3, 5, 4
b = 1, -3, 4, 9
c = []
list(zip(a,b))
for item in zip(a,b):
    c.append(item[0] + item[1])
print(c)

[3, 0, 9, 13]


In [8]:
# 
a = 2, 3, 5, 4
b = 1, -3, 4, 9
c = []
list(zip(a,b))
for x,y in zip(a,b):
    c.append(x + y)
print(c)

[3, 0, 9, 13]


# Numpy

In [9]:
import numpy as np
# pick a list and comvert it to a numpy array
a = np.array(a)
b = np.array(b)
c = a+b
print(a)
print(b)
print(c)

[2 3 5 4]
[ 1 -3  4  9]
[ 3  0  9 13]


In [10]:
import numpy as np
# pick a list, tuple or a set and comvert it to a numpy array
a = np.array(a)
b = np.array(b)
c = a+b
print(a)
print(b)
c

[2 3 5 4]
[ 1 -3  4  9]


array([ 3,  0,  9, 13])

In [11]:
import numpy as np
# pick a list and comvert it to a numpy array
a = np.array(a)
b = np.array(b)
c = a+b
d = a*b 
print(a)
print(b)
print(c)
print(d)

[2 3 5 4]
[ 1 -3  4  9]
[ 3  0  9 13]
[ 2 -9 20 36]


In [17]:
# Attributes of array.
#1. dim
print(a.ndim)

1


In [18]:
print(a.size)

4


In [19]:
print(a.dtype)

int32


In [22]:
c = np.array([2, 4, 9, 3.2])
print(c.dtype)
print(c.shape)
c

float64
(4,)


array([2. , 4. , 9. , 3.2])

In [23]:
x = np.array([[4,9],
             [7,2],
             [1.4,1]])
print(x.ndim)
print(x.size)
print(x.shape)
print(x.dtype)

2
6
(3, 2)
float64


In [26]:
# arange in numpy
a =np.arange(5)
b =np.arange(4,8,1.2)
c =np.linspace(10,40)
print(a)
print(b)
print(c)


[0 1 2 3 4]
[4.  5.2 6.4 7.6]
[10.         10.6122449  11.2244898  11.83673469 12.44897959 13.06122449
 13.67346939 14.28571429 14.89795918 15.51020408 16.12244898 16.73469388
 17.34693878 17.95918367 18.57142857 19.18367347 19.79591837 20.40816327
 21.02040816 21.63265306 22.24489796 22.85714286 23.46938776 24.08163265
 24.69387755 25.30612245 25.91836735 26.53061224 27.14285714 27.75510204
 28.36734694 28.97959184 29.59183673 30.20408163 30.81632653 31.42857143
 32.04081633 32.65306122 33.26530612 33.87755102 34.48979592 35.10204082
 35.71428571 36.32653061 36.93877551 37.55102041 38.16326531 38.7755102
 39.3877551  40.        ]


In [27]:
a =np.arange(5)
b =np.arange(4,8,1.2)
c =np.linspace(10,40,15)
print(a)
print(b)
print(c)

[0 1 2 3 4]
[4.  5.2 6.4 7.6]
[10.         12.14285714 14.28571429 16.42857143 18.57142857 20.71428571
 22.85714286 25.         27.14285714 29.28571429 31.42857143 33.57142857
 35.71428571 37.85714286 40.        ]


In [30]:
k =np.random.randint(5)
print(k)

1
