# Assignment 1

## Study splitting and stacking of arrays in numpy.

In [2]:
# numpy.split()
# The numpy.split() function divides an array into subarrays along a specified axis. 
# It takes three parameters: the array to split, the number of splits, and the axis along which to split.
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
np.split(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [15]:
b = np.arange(1,13)

print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
np.split(b,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [17]:
# numpy.stack()
# The numpy.stack() function joins arrays along a new axis. It takes a sequence of arrays and the axis parameter
# (default is 0).

import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays along a new axis (axis 0)
stacked_array = np.stack((array1, array2))

print("Array 1:", array1)
print("Array 2:", array2)
print("Stacked Array:", stacked_array)


Array 1: [1 2 3]
Array 2: [4 5 6]
Stacked Array: [[1 2 3]
 [4 5 6]]


# Assignment 2. Look at fancy indexing, boolean arrays and masking. 

In [1]:
 # 1. Fancy Indexing:
# Fancy indexing involves using arrays of indices or arrays of boolean values to access specific 
# elements of an array. It provides a way to access and modify elements based on specified index arrays.

# Example:

import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Fancy indexing using an array of indices
indices = np.array([1, 3, 4])
selected_elements = arr[indices]

print("Original Array:", arr)
print("Selected Elements:", selected_elements)

Original Array: [1 2 3 4 5]
Selected Elements: [2 4 5]


In [2]:
import numpy as np

# create a numpy array
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# select elements at index 1, 2, 5, 7
select_elements = array1[[1, 2, 5, 7]]

print(select_elements)

[2 3 6 8]


In [3]:
# 2. Boolean Arrays:
# Boolean arrays involve creating an array of boolean values based on a certain condition. 
# These boolean arrays can then be used for indexing or masking operations.

# Example:
import numpy as np

# create an array of numbers
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# create a boolean mask
boolean_mask = array1 % 2 != 0

# boolean indexing to filter the odd numbers
result = array1[boolean_mask]

print(result)


[1 3 5 7 9]


In [4]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# create a boolean mask
boolean_mask = array2 % 2 == 0

# boolean indexing to filter the odd numbers
result = array2[boolean_mask]

print(result)

[ 2  4  6  8 10]


In [5]:
import numpy as np

# create a 2D  array
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = array1 > 9

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)

[14 19 21 25 29 35]


# Assignment 3. Write on the advantages and disadvantages of outlier.

# Advantages of Outliers:

### 1. Identification of Anomalies: Outliers can help identify anomalies or unusual behavior in the data. 
### Detecting these unusual observations may lead to insights or discoveries that can be valuable in certain situations.

### 2. Signal of Potential Issues: Outliers might indicate errors in data collection or processing. 
### Identifying and addressing these errors is crucial for maintaining data accuracy and reliability.

# Disadvantages of Outliers:

### 1. Impact on Statistical Measures: Outliers can significantly affect statistical measures such as mean and 
### standard deviation. The mean, in particular, is sensitive to extreme values, and if outliers 
### are not handled properly,  they can distort the interpretation of the central tendency of the data.

### 2. Skewing Data Distribution: Outliers can skew the distribution of the data, making it non-normally distributed. 
### This can affect the validity of certain statistical tests that assume a normal distribution.

### 3. Influence on Machine Learning Models: Outliers may have a substantial impact on the performance of 
### some machine learning models, especially those sensitive to variations in the input data. 
### They can introduce noise and lead the model to learn patterns that don't generalize well to new data.

### 4. Misinterpretation of Results: If outliers are not properly understood or addressed,they can lead to misinterpretation 
### of the results of data analyses. Conclusions drawn without considering outliers may be inaccurate or incomplete.